import { CheckCircleIcon } from '@heroicons/react/24/outline';

export interface FeedbackSummaryProps {
    summary: string;
    isLoading: boolean;
}

export function FeedbackSummary({ summary, isLoading }: FeedbackSummaryProps) {
    if (isLoading) {
        return (
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 animate-pulse">
                <div className="flex items-center space-x-4 mb-4">
                    <div className="h-10 w-10 bg-blue-100 rounded-full"></div>
                    <div className="h-4 bg-gray-200 rounded w-1/4"></div>
                </div>
                <div className="space-y-3">
                    <div className="h-3 bg-gray-100 rounded w-full"></div>
                    <div className="h-3 bg-gray-100 rounded w-5/6"></div>
                    <div className="h-3 bg-gray-100 rounded w-4/6"></div>
                </div>
            </div>
        );
    }

    if (!summary) return null;

    return (
        <div className="bg-gradient-to-br from-indigo-50 to-blue-50 rounded-xl p-6 border border-indigo-100 shadow-sm relative overflow-hidden">
            <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-blue-100 rounded-full opacity-50 blur-xl"></div>

            <div className="flex items-start relative z-10">
                <div className="flex-shrink-0 bg-white p-2 rounded-lg shadow-sm">
                    <svg className="h-6 w-6 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                </div>
                <div className="ml-4 flex-1">
                    <h3 className="text-lg font-bold text-indigo-900">AI Performance Insights</h3>
                    <div className="mt-3 prose prose-sm text-indigo-800 max-w-none">
                        <p className="leading-relaxed">{summary}</p>
                    </div>
                    <div className="mt-4 flex items-center text-xs text-indigo-600 font-medium">
                        <CheckCircleIcon className="h-4 w-4 mr-1" />
                        Generated by NovaAI based on submitted reviews
                    </div>
                </div>
            </div>
        </div>
    );
}
