import { Router } from 'express';
import analyticsRoutes from './analytics.routes';
import assetRoutes from './assetRoutes';
import attendanceRoutes from './attendanceRoutes';
import authRoutes from '../modules/auth/auth.routes';
import benefitsRoutes from '../modules/benefits/benefits.routes';
import complianceRoutes from './complianceRoutes';
import dashboardRoutes from './dashboardRoutes';
import departmentRoutes from './departmentRoutes';
import documentsRoutes from '../modules/documents/documents.routes';
import employeeRoutes from './employeeRoutes';
import expenseRoutes from '../modules/expense/expense.routes';
import goalsRoutes from '../modules/goals/goals.routes';
import leaveRoutes from './leaveRoutes';
import notificationRoutes from '../modules/notification/notification.routes';
import offboardingRoutes from '../modules/offboarding/offboarding.routes';
import onboardingRoutes from '../modules/onboarding/onboarding.routes';
import payrollRoutes from '../modules/payroll/payroll.routes';
import performanceRoutes from './performance.routes';
import recruitmentRoutes from './recruitmentRoutes';
import reportRoutes from './reportRoutes';
import roleRoutes from './roleRoutes';
import settingsRoutes from './settingsRoutes';
import shiftRoutes from '../modules/shift/shift.routes';
import timeTrackingRoutes from '../modules/time-tracking/time-tracking.routes';
import trainingRoutes from '../modules/training/training.routes';

const router = Router();

// Core routes
router.use('/analytics', analyticsRoutes);
router.use('/assets', assetRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/auth', authRoutes);
router.use('/benefits', benefitsRoutes);
router.use('/compliance', complianceRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/departments', departmentRoutes);
router.use('/documents', documentsRoutes);
router.use('/employees', employeeRoutes);
router.use('/expenses', expenseRoutes);
router.use('/goals', goalsRoutes);
router.use('/leave', leaveRoutes);
router.use('/notifications', notificationRoutes);
router.use('/offboarding', offboardingRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/payroll', payrollRoutes);
router.use('/performance', performanceRoutes);
router.use('/recruitment', recruitmentRoutes);
router.use('/reports', reportRoutes);
router.use('/roles', roleRoutes);
router.use('/settings', settingsRoutes);
router.use('/shifts', shiftRoutes);
router.use('/time-tracking', timeTrackingRoutes);
router.use('/training', trainingRoutes);

export default router;
